#!/usr/bin/env python3
import os
import urllib.request
from PIL import Image, ImageDraw

PROJECT_NAME = "FFZYTV"
PACKAGE_NAME = "com.ffzy.tv"

# Official gradlew script (Linux/macOS) - Gradle 8.3
GRADLEW_CONTENT = r'''#!/bin/bash

##############################################################################
#
#  Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

PRG="$0"
while [[ -h "$PRG" ]] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
    echo "❌ gradle-wrapper.jar is missing!"
    exit 1
fi

JAVACMD="java"
which java >/dev/null 2>&1 || { echo >&2 "Java is required but not found."; exit 1; }

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  -Dorg.gradle.appname="`basename "$0"`" -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
'''

def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

def download_file(url, dest):
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    print(f"📥 Downloading {os.path.basename(dest)} from {url} ...")
    urllib.request.urlretrieve(url, dest)

def main():
    root = PROJECT_NAME
    src = os.path.join(root, "app", "src", "main")
    java_root = os.path.join(src, "java", *PACKAGE_NAME.split("."))
    res = os.path.join(src, "res")

    # Create all necessary directories upfront
    os.makedirs(java_root, exist_ok=True)
    for d in ["values", "layout", "drawable", "mipmap-xxxhdpi"]:
        os.makedirs(os.path.join(res, d), exist_ok=True)

    # === settings.gradle ===
    write_file(os.path.join(root, "settings.gradle"), f"rootProject.name = '{PROJECT_NAME}'\ninclude ':app'\n")

    # === Project build.gradle ===
    write_file(os.path.join(root, "build.gradle"), """\
plugins {
    id 'com.android.application' version '8.3.0' apply false
}
""")

    # === App build.gradle ===
    write_file(os.path.join(root, "app", "build.gradle"), f"""\
plugins {{
    id 'com.android.application'
}}

android {{
    namespace '{PACKAGE_NAME}'
    compileSdk 34
    defaultConfig {{
        applicationId "{PACKAGE_NAME}"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }}
    signingConfigs {{
        release {{
            storeFile file("ffzytv.keystore")
            storePassword System.getenv("KEYSTORE_PASSWORD") ?: "mypassword"
            keyAlias System.getenv("KEY_ALIAS") ?: "ffzytv"
            keyPassword System.getenv("KEY_PASSWORD") ?: "mypassword"
        }}
    }}
    buildTypes {{
        release {{
            signingConfig signingConfigs.release
            minifyEnabled false
        }}
    }}
    compileOptions {{
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }}
}}

dependencies {{
    implementation 'androidx.core:core-ktx:1.12.0'
}}
""")

    # === AndroidManifest.xml ===
    write_file(os.path.join(src, "AndroidManifest.xml"), f"""\
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@android:style/Theme.Material.NoActionBar">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:banner="@drawable/banner">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LEANBACK_LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
""")

    # === strings.xml ===
    write_file(os.path.join(res, "values", "strings.xml"), '<resources>\n<string name="app_name">FFZYTV</string>\n</resources>')

    # === MainActivity.java ===
    write_file(os.path.join(java_root, "MainActivity.java"), """\
package com.ffzy.tv;
import android.app.Activity;
import android.os.Bundle;
public class MainActivity extends Activity {
    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}
""")

    # === activity_main.xml ===
    write_file(os.path.join(res, "layout", "activity_main.xml"), """\
<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center"
    android:text="FFZYTV\\nhttps://cj.ffzyapi.com/"
    android:textColor="#FFFFFF"
    android:background="#2C3E50"/>
""")

    # === Generate icons ===
    def create_icon(text, size, bg, fg):
        img = Image.new("RGB", (size, size), bg)
        draw = ImageDraw.Draw(img)
        draw.text((size // 2, size // 2), text, fill=fg, anchor="mm")
        return img

    ic_launcher = create_icon("FF", 144, (70, 130, 180), (255, 255, 255))
    banner = create_icon("FFZYTV", 320, (41, 128, 185), (255, 255, 255))

    ic_launcher.save(os.path.join(res, "mipmap-xxxhdpi", "ic_launcher.png"))
    banner.save(os.path.join(res, "drawable", "banner.png"))

    # === Gradle Wrapper Files ===
    write_file(os.path.join(root, "gradlew"), GRADLEW_CONTENT)
    os.chmod(os.path.join(root, "gradlew"), 0o755)

    write_file(os.path.join(root, "gradle", "wrapper", "gradle-wrapper.properties"),
"""distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.3-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
""")

    # ✅ Download real gradle-wrapper.jar from official Gradle 8.3 distribution
    jar_url = "https://downloads.gradle.org/distributions/gradle-8.3-bin.zip"
    # But we only need the wrapper jar, which is inside the zip at: gradle-8.3/lib/gradle-wrapper-8.3.jar
    # However, easier: use the pre-extracted one from a known CDN or GitHub mirror.

    # Alternative: Use direct link to gradle-wrapper.jar from Gradle's own repo
    wrapper_jar_url = "https://repo.gradle.org/gradle/dist-snapshots/gradle-wrapper-8.3.jar"
    jar_path = os.path.join(root, "gradle", "wrapper", "gradle-wrapper.jar")
    download_file(wrapper_jar_url, jar_path)

    print(f"✅ Project '{PROJECT_NAME}' generated with downloaded gradle-wrapper.jar!")
    print("🚀 Now './gradlew assembleRelease' will work!")

if __name__ == "__main__":
    main()
