plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ffzy.tv'
    compileSdk 34
    defaultConfig {
        applicationId "com.ffzy.tv"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
}
